# Generated by Django 2.2 on 2019-08-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='measurements_format',
            field=models.IntegerField(choices=[(1, 'USA'), (2, 'EUROPE')], default=1),
        ),
    ]
