# Generated by Django 2.2 on 2019-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_measurements_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='measurements_format',
            field=models.CharField(choices=[('USA', 'USA (default)'), ('Europe', 'Europe')], default='USA', max_length=55),
        ),
    ]
