# Generated by Django 2.2 on 2019-07-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20190614_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='first_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='goalie',
            name='height_inches',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='goalie',
            name='last_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='skater',
            name='first_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='skater',
            name='height_inches',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='skater',
            name='last_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='skater',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='skater',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skt', to='players.Team'),
        ),
    ]
