# Generated by Django 2.2 on 2019-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20190702_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='draft_number_int',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='draft_round_int',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='draft_year_int',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AddField(
            model_name='skater',
            name='draft_number_int',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AddField(
            model_name='skater',
            name='draft_round_int',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AddField(
            model_name='skater',
            name='draft_year_int',
            field=models.IntegerField(default=25, null=True),
        ),
    ]
