# Generated by Django 2.2 on 2019-07-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20190702_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalie',
            old_name='draft_number_int',
            new_name='draft_number',
        ),
        migrations.RenameField(
            model_name='goalie',
            old_name='draft_round_int',
            new_name='draft_round',
        ),
        migrations.RenameField(
            model_name='goalie',
            old_name='draft_year_int',
            new_name='draft_year',
        ),
        migrations.RenameField(
            model_name='skater',
            old_name='draft_number_int',
            new_name='draft_number',
        ),
        migrations.RenameField(
            model_name='skater',
            old_name='draft_round_int',
            new_name='draft_round',
        ),
        migrations.RenameField(
            model_name='skater',
            old_name='draft_year_int',
            new_name='draft_year',
        ),
    ]
