# Generated by Django 2.2 on 2019-08-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20190820_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='height_inches',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='height_inches',
        ),
    ]
