# Generated by Django 2.2 on 2019-09-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20190820_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='draft_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='draft_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='draft_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skater',
            name='draft_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skater',
            name='draft_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skater',
            name='draft_year',
            field=models.IntegerField(null=True),
        ),
    ]
