# Generated by Django 2.2 on 2019-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20190903_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='nation_abbr',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='skater',
            name='nation_abbr',
            field=models.CharField(default='', max_length=128),
        ),
    ]
