# Generated by Django 2.2 on 2019-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_auto_20190903_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='draft_year',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='skater',
            name='draft_year',
            field=models.IntegerField(default=25),
        ),
    ]
