# Generated by Django 2.2 on 2019-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_auto_20190903_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='draft_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skater',
            name='draft_year',
            field=models.IntegerField(null=True),
        ),
    ]
