# Generated by Django 2.2 on 2019-09-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_auto_20190903_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='nation',
            field=models.CharField(default='ALALA', max_length=128),
        ),
        migrations.AlterField(
            model_name='skater',
            name='nation',
            field=models.CharField(default='ALALA', max_length=128),
        ),
    ]
