# Generated by Django 2.2 on 2019-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_auto_20190903_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='nation',
            field=models.CharField(default='AAAAAAAAAAAAAAAAA', max_length=128),
        ),
        migrations.AlterField(
            model_name='skater',
            name='nation',
            field=models.CharField(default='AAAAAAAAAAAAAAAAA', max_length=128),
        ),
    ]
