# Generated by Django 2.2 on 2019-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0043_auto_20190916_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='video_link_updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='skater',
            name='video_link_updated_at',
            field=models.DateField(),
        ),
    ]
