# Generated by Django 2.2 on 2019-09-19 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0049_auto_20190917_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='relevant_video',
        ),
        migrations.RemoveField(
            model_name='skater',
            name='relevant_video',
        ),
        migrations.AlterField(
            model_name='goalie',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2018, 9, 19)),
        ),
        migrations.AlterField(
            model_name='skater',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2018, 9, 19)),
        ),
    ]
