# Generated by Django 2.2 on 2019-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0054_auto_20190920_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='draft_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skater',
            name='draft_year',
            field=models.IntegerField(null=True),
        ),
    ]
