# Generated by Django 2.2 on 2019-09-25 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0056_auto_20190925_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='boxscore',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
