# Generated by Django 2.2 on 2019-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0057_goalie_boxscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='boxscore',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='shotouts',
        ),
        migrations.AddField(
            model_name='game',
            name='test',
            field=models.FloatField(default=1.0),
        ),
    ]
