# Generated by Django 2.2 on 2019-09-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0058_auto_20190925_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
