# Generated by Django 2.2 on 2019-09-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0060_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='test',
        ),
    ]
