# Generated by Django 2.2 on 2019-09-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0063_gameday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameday',
            old_name='date',
            new_name='day',
        ),
    ]
