# Generated by Django 2.2 on 2019-09-26 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0065_auto_20190926_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2018, 9, 26)),
        ),
    ]
