# Generated by Django 2.2 on 2019-09-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0068_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
