# Generated by Django 2.2 on 2019-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0069_remove_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.CharField(max_length=128),
        ),
    ]
