# Generated by Django 2.2 on 2019-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0071_auto_20190926_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.TextField(),
        ),
    ]
