# Generated by Django 2.2 on 2019-09-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0074_auto_20190927_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
