# Generated by Django 2.2 on 2019-09-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0075_remove_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.CharField(default='', max_length=128),
        ),
    ]
