# Generated by Django 2.2 on 2019-09-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0077_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team',
        ),
    ]
