# Generated by Django 2.2 on 2019-09-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0079_auto_20190927_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
