# Generated by Django 2.2 on 2019-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0081_game_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(default='', max_length=128),
        ),
    ]
