# Generated by Django 2.2 on 2019-09-30 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0082_auto_20190927_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='goalies',
            field=models.ManyToManyField(blank=True, related_name='roster_goalies', to='players.Goalie'),
        ),
        migrations.AddField(
            model_name='game',
            name='skaters',
            field=models.ManyToManyField(blank=True, related_name='roster_skaters', to='players.Skater'),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='day',
            field=models.DateField(default=datetime.date(2018, 9, 30), unique=True),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2018, 9, 30)),
        ),
        migrations.AlterField(
            model_name='skater',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2018, 9, 30)),
        ),
    ]
