# Generated by Django 2.2 on 2019-09-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0083_auto_20190930_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='goalies',
        ),
        migrations.RemoveField(
            model_name='game',
            name='skaters',
        ),
    ]
