# Generated by Django 2.2 on 2019-09-30 09:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0086_auto_20190930_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='new_gamelog_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='skater',
            name='new_gamelog_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
