# Generated by Django 2.2 on 2019-10-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0089_auto_20191001_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teams',
        ),
    ]
