# Generated by Django 2.2 on 2019-10-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0090_remove_game_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='teams_m2m',
            new_name='teams',
        ),
        migrations.RemoveField(
            model_name='game',
            name='boxscore',
        ),
    ]
