# Generated by Django 2.2 on 2019-10-04 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='day',
            field=models.DateField(default=datetime.date(2018, 10, 4), unique=True),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2018, 10, 4)),
        ),
        migrations.AlterField(
            model_name='skater',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2018, 10, 4)),
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(default='', max_length=128)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
        ),
    ]
