# Generated by Django 2.2 on 2019-10-04 12:24
import datetime

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Game = apps.get_model('players', 'Game')
    Side = apps.get_model('players', 'Side')
    for game in Game.objects.all():
        for team in game.teams.all():
            Side(
                team=team,
                game=game,
                side=''
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20191004_1518'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
