# Generated by Django 2.2 on 2019-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_game_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_games', through='players.Side', to='players.Team'),
        ),
    ]
