# Generated by Django 2.2.6 on 2020-01-09 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20191017_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='day',
            field=models.DateField(default=datetime.date(2019, 1, 9), unique=True),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2019, 1, 9)),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skater',
            name='video_link_updated_at',
            field=models.DateField(default=datetime.date(2019, 1, 9)),
        ),
    ]
