# Generated by Django 2.2.6 on 2023-11-15 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_auto_20231110_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='day',
            field=models.DateField(default=datetime.date(2022, 11, 15), unique=True),
        ),
    ]
