# Generated by Django 2.2.6 on 2023-11-16 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_auto_20231116_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='day',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
