# Generated by Django 2.2.6 on 2023-12-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0040_gameday_all_games_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_final',
            field=models.BooleanField(default=False),
        ),
    ]
