# Generated by Django 2.2.6 on 2026-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0045_auto_20240109_2257"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalie",
            name="stats_season_id",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="skater",
            name="stats_season_id",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
